# Custom Language File for Launcher Customizer

[ejs.app]
title = "츄타듀밸리"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/ChutadewValley"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/ChutadewValley"
supportLink = "https://github.com/CustomLauncherLab/ChutadewValley/issues"

[ejs.welcome]
welcomeHeader = "츄타듀밸리"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."